version: "3.8"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compro_sena_admin1
    volumes:
      - .:/var/www
      - /var/www/vendor
    ports:
      - "4343:8000"
